project_id = "vljagrtdnaqmoppcjjsf"

[functions.ai-route-suggestions]
verify_jwt = false

[functions.ai-training-insights]
verify_jwt = false

[functions.generate-cycling-route]
verify_jwt = false

[functions.geocode-location]
verify_jwt = false
